services:
  db:
    image: postgres:16
    container_name: eth-portfolio-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build: .
    container_name: eth-portfolio-web
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/portfolio
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: replace-with-strong-secret
      ETHERSCAN_API_KEY: 8XUVQC68W5N9SGEIWQJIQQT7YCEUZ8DKYT
      ETHERSCAN_API_BASE: https://api.etherscan.io/v2/api
      ETHERSCAN_CHAIN_ID: "1"
      COINGECKO_API_BASE: https://api.coingecko.com/api/v3
      PRICE_BUCKET_SECONDS: "3600"
      DEFAULT_WALLET_ADDRESS: 0xaAcCAf0C21Ad6D1d048E56171ABdabAf60B717dc
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data:
